kind: Deployment
apiVersion: apps/v1
metadata:
  name: lights-backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-backend
  template:
    metadata:
      labels:
        app: lights-backend 
    spec:
      containers:
        - name: lights-backend
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: lights-backend
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30421
  selector:
    app: lights-backend
