kind: Deployment
apiVersion: apps/v1
metadata:
  name: lights-backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-backend
  template:
    metadata:
      labels:
        app: lights-backend 
    spec:
      containers:
        - name: lights-backend
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: lights-backend
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: lights-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: lights-backend
  namespace: prod
spec:
  tls:
    - hosts:
        - lights-socket.jodios.com
      secretName: lights-backend-prod-tls
  rules:
    - host: lights-socket.jodios.com
      http:
        paths:
          - backend:
              service:
                name: lights-backend
                port:
                  number: 8080
            pathType: ImplementationSpecific