kind: Deployment
apiVersion: apps/v1
metadata:
  name: lights-frontend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-frontend
  template:
    metadata:
      labels:
        app: lights-frontend 
    spec:
      containers:
        - name: lights-frontend
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: lights-frontend
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: lights-frontend
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: lights-frontend
  namespace: prod
spec:
  rules:
  - host: lights.jodios.com
    http:
      paths:
      - backend:
          serviceName: lights-frontend
          servicePort: 80